version: "3"
services:
  frontend:
    image: carshow
    environment:
      - ALLOW_OVERRIDE=true
    ports:
      - "81:80"
      - "4433:443"
    links:
      - db
    volumes:
      - ./app:/var/www/html/
      - ./app/logs:/var/log/apache2
      - ./certificados:/var/imported/ssl
      - ./virtualhost/carshow.conf:/etc/apache2/sites-available/carshow.conf 
  backend:
    image: python:3.8